services:
  - type: web
    name: agrisat-backend
    env: python
    buildCommand: pip install -r simple_requirements.txt
    startCommand: uvicorn simple_main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true 