services:
  - type: web
    name: agrisat-backend
    runtime: python
    pythonVersion: "3.10"
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=8000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NASA_USERNAME
        sync: false
      - key: NASA_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.10" 