services:
  - type: web
    name: agrisat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NASA_USERNAME
        sync: false
      - key: NASA_PASSWORD
        sync: false
    autoDeploy: true
    plan: free 