services:
  - type: web
    name: agrisat-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NASA_USERNAME
        sync: false
      - key: NASA_PASSWORD
        sync: false
    autoDeploy: true 